# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='video', max_length=500),
        ),
    ]
