# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20161024_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='published_at',
            field=models.DateTimeField(default=None),
        ),
    ]
