# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_reply_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['published_at']},
        ),
    ]
