# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20161024_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
