# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20161103_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='videos',
            field=models.ManyToManyField(to='video.Video'),
        ),
    ]
