# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_worker_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
