# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20161104_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
