# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_reply_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='avg_completion_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
