# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_video_avg_completion_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='video',
            name='avg_completion_rate',
        ),
        migrations.AddField(
            model_name='video',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
